version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/backend_server
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: frontend/Dockerfile
    ports:
      - "9200:80"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: changemeinprod
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    build:
      context: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
