version: '3.8'

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: changemeinprod
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      local:



  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: nongtiensonpro/deployment-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/backend_server
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: nongtiensonpro/deployment-frontend:latest
    ports:
      - "3000:80"



  nginx:
    build:
      context: ./nginx
    image: nongtiensonpro/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    restart: always
    ports:
      - "9082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: postgres  # Đảm bảo user này đúng
      KC_DB_PASSWORD: changemeinprod  # Mật khẩu đúng
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak  # Địa chỉ database
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    depends_on:
      - postgres
    networks:
      - local
    volumes:
      - keycloak_data:/opt/keycloak/data



volumes:
  postgres_data:
  keycloak_data:

networks:
  local:
    driver: bridge